### PR TITLE
big refactor, mainly for better readability

### PR DESCRIPTION
**Pull request by ctrlsam**
broke up the code into functions and made pep-8 compliant.

### CODE REVIEW

**Comment by ctrlsam** [comment]
Added a new banner

**Comment by PinkDev1** [comment]
Wow, those are a lot of changes!
Maybe the repo-maintainter will want to review and analyze if your changes are good or not, but if I were him I'd close this PR right away; You can't expect maintainers to aprove such a **massive** change with minimal/non-existent documentation on wich changes you made.
For higher chances of your changes merged, consider making better documentation/comments on what changes you made.

I do appreciate the banner tho

**Comment by mxrch** [comment]
Thank you, I'll take a look at it.
I'll just take time before it to merge the other little PRs to avoid conflicting changes !
I like the banner too 😊

**Comment by ctrlsam** [comment]
Yip no worries, please give feedback if you don't like something I did, will be happy to fix it up. Otherwise cool project and hope my contributions helped :)

**Comment by ctrlsam** [comment]
@mxrch any chance you could set the label for this PR to be "hacktoberfest-accepted"?

**Comment by Hammond95** [comment]
Hi @ctrlsam , you did a nice job, can we get in contact so that we can join our efforts?
I am working on PR #72

**Comment by mxrch** [comment]
I'm currently reviewing it and fixing a few things, you did a pretty good job.

**Comment by ctrlsam** [comment]
@Hammond95 yea sure, do u have discord?

**Comment by ctrlsam** [comment]
@mxrch sweet as. I'll have a look at what else I can do

**Pull request merged**
