### PR TITLE
Added Google Calendar exposure and feature to run ghunt from any dir 

### PR DESCRIPTION
**Pull request by NikolozCh**
Added support for fetching public calendar details for the specific person with email. Maybe it needs optimization, I don't know at this moment.

TODO: I think there should be way somehow to check if user has calendar public or not without starting chromedriver

Added new library in requirements.txt: `bs4` (not `bs4` longer)
Edit: Added new library in requirements.txt: `Scrapy`

- It is used to parse the html from calendar, since google doesn't send calendar data in `JSON` or `XML`

### CODE REVIEW

**Comment by mxrch** [comment]
Hey, very cool you used httpx and the tmprinter :wink: I'll look at it when I'm not busy anymore !
By the way, wasn't there a way to do it without selenium? Like just fetch the page and then use the source code? Or was there lazy loading?

2nd question, can you use Scrapy instead of BeautifulSoup ? It has better performance and I would like to make the project easily convertible to async, which Scrapy supports. 😊
I don't think it needs a lot of changes in your PR

**Comment by NikolozCh** [comment]
Hello!

Thanks for your interest in my pull request!

Of course I will change BeautifulSoap to Scrapy. Since I know the structure it must not be hard!

About Selenium... Unfortunately, no, I was not. I had suffered from pain implementing fetching without selenium, but I was not able still... I will take a look again and again. There must be a way around, but who knows.. more clever people than me can find it faster than me, haha!

I will push it as soon as I change bs4 to Scrapy and will let you know.

Cheers!

**Comment by mxrch** [comment]
No problem, just to be sure 😄 
Cheers !

**Comment by NikolozCh** [comment]
By the way, did you like the idea with check_and_gen.py? I think option to change already existing cookies is necessary to be implemented. Isn't it?

**Pull request merged**
