### PR TITLE
Added retries

### PR DESCRIPTION
**Pull request by Derpyhsi**
Added retries incase it fails the first time to retrieve the request. I set the max retries to 3.

### CODE REVIEW

**Comment by PinkDev1** [comment]
Retrieving "blockedPeople" has never failed for me. Has it for you?

**Comment by Derpyhsi** [comment]
It keeps timing out for me even with retries.

**Comment by PinkDev1** [comment]
Well that's weird. You might want to open an issue so we can further investigate this

**Comment by Derpyhsi** [comment]
@PinkDev1 https://github.com/mxrch/GHunt/issues/56

**Comment by mxrch** [comment]
Yes, if it doesn't works the first time I don't think adding retries would fix a thing, it's better to open an issue.

**Pull request closed without merging**
