### PR TITLE
Update check_and_gen.py

### PR DESCRIPTION
**Pull request by KrishSai1997**
This is my First Pull request so don't mind if I did something wrong :P

### CODE REVIEW

**Comment by mxrch** [comment]
Hey @KrishSai1997 , can you tell me what it's doing if you run in with no-sandbox and as an user on Linux ? No errors ?

**Comment by KrishSai1997** [comment]
**Before Upgrading the Packages as u suggested in Issue #11 ,I got the Following Error: **

Traceback (most recent call last):
File "check_and_gen.py", line 74, in
driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in init
super().init(*args, **kwargs)
TypeError: init() got an unexpected keyword argument 'options'

**After Upgrading my Packages, It Fixed the above error. But now, The Tool can't write/create Files inside of /opt/GHunt/ as I'm not running it as Root User.**
I Copied the GHunt Folder to Desktop and tried it from there and It works. 
The issue is because, The **/opt/** directory is owned by **Root** so, a normal user can't don't have Write Access to it.

The Files That are being Written are:
**data.txt (Created when running the check_and_gen.py) &**
**tmp.html (Created while running the hunt.py)**

**Comment by mxrch** [comment]
Yes sorry I forgot to mention "after moving the ghunt folder to a folder you own" 😄 does the --no-sandbox chrome argument you added in the pull request makes an error or is it okay ?

**Comment by KrishSai1997** [comment]
No I didn't get any errors when I tested it from the Directory which I own. And Infact it did a pretty good job finding my Location. 

Check For The File Permissions:
┌─[sai@parrot]─[~/Desktop/tmp/GHunt]
└──╼ $ls -lad && whoami
drwxr-xr-x 1 sai sai 240 Oct  3 23:04 .
sai

**Review by PinkDev1 — APPROVED** [review]

**Pull request merged**
