### PR TITLE
Added chrome driver auto-installer

### PR DESCRIPTION
**Pull request by anatolec**
Added a dependency to the chromedriver_autoinstaller package so that the correct chrome driver is automatically installed without any user input.

### CODE REVIEW

**Review by PinkDev1 — APPROVED** [review]

**Comment by mxrch** [comment]
Good idea but doesn't work on my computer :
```>>> import chromedriver_autoinstaller
>>> chromedriver_autoinstaller.install()
'C:\\Users\\mxrch\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\chromedriver_autoinstaller\\85\\chromedriver.exe'
>>> glob('**/chromedriver*')
[]```

**Comment by anatolec** [comment]
> Good idea but doesn't work on my computer :
> 
> ```
> >>> import chromedriver_autoinstaller
> >>> chromedriver_autoinstaller.install()
> 'C:\\Users\\mxrch\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\chromedriver_autoinstaller\\85\\chromedriver.exe'
> >>> glob('**/chromedriver*')
> []
> ```

Hey mxrch,
Yes you need to do `chromedriver_autoinstaller.install(cwd=True)` so that the driver is installed inside the project's directory.

Then glob should find it correctly

**Comment by mxrch** [comment]
My bad, I missed that argument.
I'm just adding a commit to make that cleaner !

**Comment by mxrch** [comment]
@anatolec @PinkDev1 are you ok with these changes ?

**Review by PinkDev1 — APPROVED** [review]

**Pull request merged**
