### PR TITLE
Create Readme

### PR DESCRIPTION
**Pull request by Arjun-thakor-005**
Help by writing #coments in code

### CODE REVIEW

**Comment by PinkDev1** [comment]
????
`Readme` isn't even the correct file. This project already has a **`README.md`**.
Also, a request for help shouldn't be in the README, it should be on the `COLLABORATING.md` file.

**Comment by Arjun-thakor-005** [comment]
Ok . I understand .
Pls accept my pull request

**Comment by outime** [comment]
@PinkDev1 these guys are just spammers, see https://blog.domenic.me/hacktoberfest/ to understand a bit of context. Report, block him and move on.

**Comment by mxrch** [comment]
@outime Yes, thank you.

**Comment by PinkDev1** [comment]
> @PinkDev1 these guys are just spammers, see https://blog.domenic.me/hacktoberfest/ to understand a bit of context. Report, block him and move on. @mxrch you may close this PR.

All of this nonsense for a goddamn T-Shirt?!
_sigh_

**Pull request closed without merging**
