### PR TITLE
Getting back first and last names

### LINKED ISSUE #508: Parsing first name and last name from Google Account by email doesn't work
**Describe the bug**
When I try to get first name and last name of the account which I used to generate creds.m everything works fine, but when I try to retreive data of another account - the result is empty

**To Reproduce**
1. Run command ghunt email any email apart of that which has been used to generate creds.m --json user_data.json

**Expected behavior**
Retreive first name and last name from Google Account

**System (please complete the following information):**
 - OS Windows 10/Linux Ubuntu 22.04.2
 - Python version 3.10.12/3.11.0

### PR DESCRIPTION
**Pull request by Epieos**
Hey @mxrch, thank you for this amazing project!

As you might have noticed, GHunt stopped printing the first and last names a few days ago.
This PR adds back this capability (fix #508) by using the *drive* context for *people_lookup*.
It also contains minor fixes for *gaia* command and *params_templates*.

Hope this helps!

### CODE REVIEW

**Comment by MeHowHere** [comment]
not working same thing

**Comment by kombumori** [comment]
Hi, @Epieos, thanks for your great PR.

Until about 3 hours ago, this PR was working fine. However, since around 3/22 2:15 (UTC), the variable `data` (line 106) in `ghunt/apis/peoplepa.py` is
`{'error': {'code': 403, 'message': 'The caller does not have permission', 'status': 'PERMISSION_DENIED'}}`
and now causes a KeyError at line 111.

Please give me a solution! 🙇‍♀️

### System
- MacOS Big Sur
- Python 3.11

*[Translated by DeepL]*

**Comment by MeHowHere** [comment]
image
change in peoplepa.py Line 29 From drive to photos

**Comment by MeHowHere** [comment]
> > image change in peoplepa.py Line 29 From drive to photos
> 
> this doesn't return names tho.

sry but it working for me
image

**Comment by kombumori** [comment]
@ilyigna 
> this doesn't return names tho.
me too

@MeHowHere

**Comment by MeHowHere** [comment]
@kombumori 

sry but i have a names i dont know how to help u with this

**Comment by mxrch** [comment]
Thanks for the fixes.

**Pull request merged**
