### PR TITLE
Add the official dependabot implementation

### PR DESCRIPTION
**Pull request by alazymeme**
This basically adds dependabot, which keeps dependencies up-to-date. Will need to create a pr label called `dependencies` for it to work correctly.

### CODE REVIEW

**Comment by PinkDev1** [comment]
How would dependabot help though?
AFAIK there are no hardcoded versions for the used packages. The `requierements.txt` file just points to the latest avalible release from PiPY

**Comment by alazymeme** [comment]
> AFAIK there are no hardcoded versions for the used packages.

Didn't see this part

> wouldn't mxrch have to give OAuth authorization for dependabot to start working?

No

**Review by adrean37 — CHANGES_REQUESTED** [review]
Não fui eu que fiz isso

**Comment by alazymeme** [comment]
Can anyone translate the above message? I don't speak Portuguese and the translation doesn't make any sense.

**Comment by mxrch** [comment]
Hey, currently I see no added value by adding dependabot, as @PinkDev1 said there is no hardcoded packages.
Thanks anyway !

**Pull request closed without merging**
