### PR TITLE
Refactored ghunt.py

### PR DESCRIPTION
**Pull request by CopernicusPY**
### Cleaned the `ghunt.py` file
This was done by removing the nested if else statements and replacing them with a dynamic function call using the `eval()` builtin.

### CODE REVIEW

**Comment by mxrch** [comment]
Hello ! The use of the `eval()` function adds nothing but a vulnerability, by executing code given in the user input. It's a big no.

**Comment by CopernicusPY** [comment]
Well in this case you cant abuse it in any way. But either way, this is a general design issue with the script. There should be a validation system, and not random len checks. I will implement this now, and open a new pr. 
-ps I didnt notice that there wasnt a input validation.

**Comment by mxrch** [comment]
@CopernicusPY No need for a new PR, I will just not implement a "dynamic" function with eval. It's dirty, and needs extra protection to protect it from injections.

**Comment by mxrch** [comment]
> *Well in this case you cant abuse it in any way*

**You can** abuse it.

image

**Pull request closed without merging**
