### PR TITLE
fix ChromeDriver version error

### PR DESCRIPTION
**Pull request by Mancy**
this update will install chromedriver of same chrome version installed in the system to avoid the version mismatch problem

### CODE REVIEW

**Review by yezz123 — APPROVED** [review]

**Comment by mxrch** [comment]
We already have a chromedriver auto-install, what does it changes ?

**Comment by Mancy** [comment]
> We already have a chromedriver auto-install, what does it changes ?

Currently the chromedriver version is fixed, but this pull request to avoid using fixed chromedriver version

**Comment by mxrch** [comment]
> 
> 
> > We already have a chromedriver auto-install, what does it changes ?
> 
> Currently the chromedriver version is fixed, but this pull request to avoid using fixed chromedriver version

What do you mean by "fixed", hardcoded ?
If yes, this is not the case and the chromedriver is actually downloaded & installed automatically

**Comment by Mancy** [comment]
>
> What do you mean by "fixed", hardcoded ?
> If yes, this is not the case and the chromedriver is actually downloaded & installed automatically

It has autoinstall if not currently installed, but later if client Chrome version updated, the current installed ChromeDriver will be used and will result in version mismatch between the Chrome version and ChromeDriver version.
the pull request will install or use ChromeDriver of the same client chrome version.

you can reproduce the error when you have ChromeDriver version older than your current Google Chrome version, then try to run check_and_gen.py with current code, then try again with this pull request

i hope this clarifies the issue

**Comment by saduqur80** [comment]
Thank

**Pull request merged**
